### PR TITLE
Optimize Chinese Localization

### PR DESCRIPTION
**Pull request by Cyrillya**
Optimized #232 and previous Chinese localizations
Translated `OptionOff`, `OptionOn` and `Search` as well
Updated zh workshop description
Re-designed difficulty levels translation, combining Chinese old sayings, memes, with Terraria stuff

### CODE REVIEW

**Comment by Cyrillya** [comment]
And there's some other things that I'd like to point out regarding the problems of #232 localization
## Why An "Optimize" Should Happen?
Partly, to fix my previous not-that-precise or literally unreadable localizations
Mainly and mostly, to remove the seemly google translated text of #232 
Then let me explain.

### Totally Machine Translated
_Gore_, as my previous translation #213, should be translated into _残骸_ (an incomplete dead body, a badly damaged object or the separated parts of a badly damaged object) to better fit the meaning and how it performs ingame. But that guy translated the thing into _暴力_, which means _Violent_ in English.

So here you, as if a Chinese player, will see: `Enable Violent Audio`, `Enable Violent Physics`, `Enable Violent Burning`, etc.
image

Here's _Sprite_, another classic in machine translation. In Chinese we often call these game assets _贴图_  (pictures that are printed to the computer screen). But #232 translated it into _精灵_, a fairy.
5f96f51b2519503082b29abb790878b1

### Not Even Plays Terraria
The Star Cannon. Everyone who speaks Chinese call the thing _星星炮_ (3 chars) instead of _星星加农炮_ (5 chars as in the pic). So I doubt if he really plays Terraria, or this is just another proof of machine translation
654096a529fe50c93e04da1440d33d43

The _Health Drops_ and _Mana Drops_ apparently mean the items dropped onto the ground which give free health & mana when picked up. He translated them into _生命值_ and _法力值_, which means _Health **Value**_ and _Mana **Value**_. Note that **Value** there
8ec8af1b5b4537b1139e80a2f87422a4


### No Respect To Previous Localization
This can be confusing for players

I've already translated _Mana Absorption_ into _魔力汲取_, but he continues to use _法力吸收_ in other text (not changing my original translation either) which highly seems machine translated.
7c6362c9be36a3f8c9462b41e58a205b
d2c6a67bf0e201d78463d3175c5b8082


So is the _Killing Blow_, he uses _击杀要害_ (killing the enemy by hitting its weak point), ignoring my _致命一击_ (a critical strike that usually ends the enemy)
8ad8b6eda9f46281d41b8ed4ced6c1b7
48e8435ac77c760fdd05763742f9340c

**Review by Mirsario — CHANGES_REQUESTED** [review]
- I've added 3 keys on the base branch: `OptionOff`, `OptionOn`, `Search`. They must now be translated. Ignore the stats that say we're at 100%.
- I've updated the workshop description texts, they must now be translated & verified against the English copy again.
- The menu button issue *should* be fixed? It's a bit confusing, could've been a thread race.

Also, no need to start fights. Even if the previous PR did happen to be google translated it's possible to say that in neutral language.

**Comment by Cyrillya** [comment]
New description is localized along with `OptionOff`, `OptionOn`, `Search`
Changed some of my previous bad localizations
Tested, the menu button issue is fixed
Apologize for sounding bad, was just too angry last night seeing the localization

I've seen that there's a new wiki set up. Can we have it translated as well? Maybe create a `/zh` page for each page available and give me the authority to edit wiki (but of course, when those pages are mostly complete and ready for translation)

**Review by Mirsario — APPROVED** [review]

**Comment by Cyrillya** [comment]
Normal: 史莱姆哥别这样
Kinda like "Slime, don't do this to me plz"

Expert: 光女你就这水平
"EoL, is that all you can do?"

Master: 吾乃克苏鲁化身
A direct translation from English using Classical Chinese

**Comment by Cyrillya** [comment]
### Difficulty levels v2

Normal: "史莱姆大哥放过我"
"Slime leave me alone plz"

Expert: "区区骷蝼何足挂齿"
"Just mere skeletons, not worth mentioning"
A pun made by replacing the "髅" in the word "骷髅" (skeleton) with "蝼" (ants, also a metaphor for tiny individuals with no power, which pronounces the same as the prior character "髅"), to emphasize that enemies in Terraria are like ants to the fearless player.

Master: "吾乃克苏鲁之化身"
A direct translation from English using Classical Chinese

**Comment by Cyrillya** [comment]
I won't be on github or discord for the next few days. I think the current translation is good enough and can be merged if you are ok with them

**Pull request merged**
